.TH OBCONF 1 2012\-04\-23 2.0.3 "Openbox Documentation"

.SH NAME
\fBObConf\fR \- configuration utility for Openbox

.SH SYNOPSIS
\fBobconf\fR [\fIOPTIONS\fR] [\fIARCHIVE.obt\fR]

.SH DESCRIPTION
\fBObConf\fR is a preferences manager for Openbox (version 3.0 and up). Its user interface is rather self-explanatory and thus does not need to be documented in this manual page.

.SH OPTIONS
.IP "--archive I\fITHEME\fR" 4
Create a theme archive from the given theme directory.
.IP "--config-file I\fIFILE\fR" 4
Specify the path to the configuration file to use.
.IP "--install I\fIARCHIVE.obt\fR" 4
Installs the given theme archive and selects it.
.IP "--tab \fINUMBER\fR" 4
Display the tab number NUMBER.
.IP "--version" 4
Displays information about the currently installed version and exists.

.SH SEE ALSO
\fIopenbox\fR(1)

.SH HOMEPAGE
More information about \fBObConf\fR and the Openbox project can be found on the homepage at <\fIhttp://www.openbox.org/\fR>.

.SH AUTHOR
\fBObConf\fR was written by Ben Jansens <\fIben@openbox.org\fR>, Dana Jansens <\fIdanakj@orodu.net\fR>, Tim Riley <\fItr@slackzone.org\fR>, and Javeed Shaikh <\fIsyscrash2k@gmail.com\fR>.
